### ISSUE TITLE
importazione csv valori immobiliare dà errore

### ISSUE THREAD

**Issue by alescotti73** [ondata/quotazioni-immobiliari-agenzia-entrate#1]
ciao ho scaricato https://github.com/ondata/quotazioni-immobiliari-agenzia-entrate/blob/master/data/QI_294577_1_20182_VALORI_utf8.csv e provato a importare in access, ho indicato fonte dati esterna, indicato prima riga come intestazione e virgola come delimitatore ma a fine import mi dà errore "il separatore di campo corrisponde al separatore decimale o al delimitatore di testo". Non sono un esperto della questione quindi può darsi sia un errore dovuto a me, ma nel dubbio sottopongo la cosa dopo aver messaggiato Andrea Borruso

grazie
Alessandro

**Comment by aborruso** [comment]
ciao @alescotti73 non uso access, ma so che quel CSV è senza errori.

Ma usando una delle procedure delle mille guide non avrai difficoltà. Una è questa https://blog.ip2location.com/knowledge-base/how-to-import-csv-into-microsoft-access-database/

In libreoffice e google drive si importa senza problemi. Basta dirgli che il separatore e la virgola

**Comment by alescotti73** [comment]
ok alla fine ho risolto importanto in excel e usando la funzionalità dati > testo in colonne, indicando virgola come separatore, grazie per l'aiuto! Ale

**Comment by aborruso** [comment]
Bene @alescotti73 secondo me è possibile direttamente da Access, ma non l'ho nemmeno installato.

L'importante che tu abbia risolto.

Cosa farai con questi dati?
